version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    container_name: minio
    restart: never
    ports:
      - "127.0.0.1:9900:9000"
      - "127.0.0.1:9901:9001"
    volumes:
      - /mnt/external/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
