services:
  nginx:
    image: nginx:1.31.6-otel
    container_name: nginx
    restart: unless-stopped
    tty: true
    network_mode: "host"
    volumes:
      - ./conf/:/etc/nginx/
      - ./letsencrypt/:/etc/letsencrypt/
      - ./ssl/:/etc/ssl/
      - ./logs/:/var/log/nginx/
      - ./client_certs:/etc/nginx/client_certs
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
