networks:
  loki:

services:
  alloy:
    container_name: grafana_alloy
    volumes:
      - ./conf:/etc/alloy
      - /var/lib/docker/containers:/host/var/lib/docker/containers
      - /opt/containers/MediaCentre/nginx/logs/:/host/var/log/nginx
      - /var/log/journal:/host/var/log/journal
    environment:
      - LOKI_ID=${LOKI_ID}
      - LOKI_TOKEN=${LOKI_TOKEN}
      - LOKI_IDEFIX_USER=${LOKI_IDEFIX_USER}
      - LOKI_IDEFIX_TOKEN=${LOKI_IDEFIX_TOKEN}
    ports:
      - 12345:12345
    image: grafana/alloy:v1.16.0
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'
    networks:
      - loki
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
