version: '3'
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.33.1
    volumes: 
      - ./zigbee2mqtt/data:/app/data
      - /un/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/London
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  homebridge:
    image: oznu/homebridge:2023-01-08
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/London
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ./homebridge:/homebridge
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#  homeassistant:
#    container_name: homeassistant
#    image: homeassistant/home-assistant:2022.9.1
#    volumes:
#      - ./homeassistant/config:/config
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
#    network_mode: host
#    logging:
#      options:
#        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
#
