services:
  ukfuelprices:
    platform: linux/amd64
    image: pascal22p/uk-fuel-prices:latest-snapshot
    container_name: ukfuelprices
    restart: unless-stopped
    environment:
      APP_SECRET: ${APP_SECRET}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PYROSCOPE_AGENT_ENABLED: true
      PYROSCOPE_APPLICATION_NAME: ${PYROSCOPE_NAME}
      PYROSCOPE_PROFILER_ALLOC: 512k
      PYROSCOPE_SERVER_ADDRESS: ${PYROSCOPE_SERVER_ADDRESS}
      PYROSCOPE_BASIC_AUTH_USER: ${PYROSCOPE_BASIC_AUTH_USER}
      PYROSCOPE_BASIC_AUTH_PASSWORD: ${PYROSCOPE_BASIC_AUTH_PASSWORD}
      PYROSCOPE_TRACE_PROFILING_ENABLED: true
      OTEL_RESOURCE_ATTRIBUTES: "service.name=genealogy,deployment.environment=prod"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-gb-south-0.grafana.net/otlp"
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
      OTEL_SERVICE_NAME: ukfuelprices
      PLAY_FILTERS_HOSTS: uk-fuel-prices.parois.net
      PROTOCOL: https://
      APP_NAME: Parois.net
      JAVA_OPTS: >-
        -Dlogger.file=/opt/logback.xml
        -javaagent:/opt/grafana-opentelemetry-java.jar
        -Dotel.javaagent.extensions=/opt/pyroscope-otel-javaagent-extension.jar
        -Dotel.instrumentation.common.default-enabled=true
        -Dotel.instrumentation.opentelemetry-annotations.enabled=true
        -Dotel.instrumentation.methods.enabled=true
        -Dotel.bsp.max.queue.size=4096
        -Dotel.bsp.max.export.batch.size=1024
        -Dotel.bsp.schedule.delay=1000
      PARTIAL_UPDATE_IS_ENABLED: true
      PARTIAL_UPDATE_JOB_INTERVAL_IN_MINUTES: 5
      PARTIAL_UPDATE_SCHEDULER_INTERVAL_IN_MINUTES: 1
      PARTIAL_UPDATE_START_DELAY_IN_SECONDS: 10
      FUEL_CLIENT_ID: ${FUEL_CLIENT_ID}
      FUEL_CLIENT_SECRET: ${FUEL_CLIENT_SECRET}
      FUEL_HOST: "172.17.0.1"
      FUEL_PORT: 9235
      FUEL_PROTOCOL: http
    ports:
      - 127.0.0.1:9234:9234
    volumes:
      - ./Config/logback.xml:/opt/logback.xml:ro
      - ./otel/grafana-opentelemetry-java.jar:/opt/grafana-opentelemetry-java.jar:ro
      - ./otel/pyroscope-otel-javaagent-extension.jar:/opt/pyroscope-otel-javaagent-extension.jar:ro
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "50m"
        max-file: "3"

