server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://172.17.0.1:3100/api/prom/push

scrape_configs:
- job_name: journal
  journal:
    json: true
    path: /host/var/log/journal
    labels:
      job: systemd-journal
      host: "abraracourcix.debroglie.net"
  relabel_configs:
  - source_labels: ['__journal__systemd_unit']
    target_label: 'unit'
    regex: 'session-[0-9]+\.scope'
    replacement: session
  - source_labels: ['__journal_syslog_identifier']
    target_label: 'syslog_identifier'
  - source_labels: ['__journal_priority']
    target_label: 'level'
  pipeline_stages:
  - template:
      source: level
      template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
  - labels:
      level:

- job_name: nginx
  static_configs:
  - targets:
      - abraracourcix.debroglie.net
    labels:
      job: nginx
      host: abraracourcix.debroglie.net
      __path__: /host/var/log/nginx/*log
  pipeline_stages:
  - json:
      expressions:
        http_host: http_host
  - labels:
      http_host:

- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      host: abraracourcix.debroglie.net
      __path__: /host/var/lib/docker/containers/*/*log
  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output

- job_name: php-fpm
  static_configs:
  - targets:
      - abraracourcix.debroglie.net
    labels:
      job: php-fpm
      host: abraracourcix.debroglie.net
      __path__: /host/var/log/php-fpm/*error.log
  pipeline_stages:
  - multiline:
      # Identify timestamps as first line of a multiline block. Enclose the string in single quotes.
      firstline: '^\[[0-9]+-[a-zA-Z]+-[0-9]+ [0-9]+:[0-9]+:[0-9]+ [^ ]+\]'
      max_wait_time: 3s
  - regex:
      # Flag (?s:.*) needs to be set for regex stage to capture full traceback log in the extracted map.
      expression: '^(?P<time>\[[0-9]+-[a-zA-Z]+-[0-9]+ [0-9]+:[0-9]+:[0-9]+ [^ ]+\]) (?P<message>(?s:.*))'

- job_name: mariadb-audit
  static_configs:
  - targets:
      - abraracourcix.debroglie.net
    labels:
      job: mariadb-audit
      host: abraracourcix.debroglie.net
      __path__: /host/var/log/mariadb/audit.log
  pipeline_stages:
  - regex:
      expression: '^(?P<time>[^,]+),(?P<serverhost>[^,]+),(?P<username>[^,]+),(?P<host>[^,]+),(?P<connectionid>[^,]+),(?P<queryid>[^,]+),(?P<operation>[^,]+),(?P<database>[^,]+),(?P<object>[^,]+),(?P<retcode>[^,]+)$'
  - labels:
      operation:
      database:
      username:
      retcode:
      
- job_name: mariadb
  static_configs:
  - targets:
      - abraracourcix.debroglie.net
    labels:
      job: mariadb
      host: abraracourcix.debroglie.net
      __path__: /host/var/log/mariadb/mariadb.log

- job_name: nextcloud
  static_configs:
  - targets:
      - abraracourcix.debroglie.net
    labels:
      job: nextcloud
      host: abraracourcix.debroglie.net
      __path__: /host/var/log/nextcloud/nextcloud.log
  pipeline_stages:
  - json:
      expressions:
        app: app
        user: user
  - labels:
      app:
      user:
