services:
  genealogy:
    platform: linux/amd64
    image: pascal22p/genealogy:latest-snapshot
    container_name: genealogy
    restart: unless-stopped
    networks:
      - dockernet
    environment:
      APP_SECRET: ${APP_SECRET}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PYROSCOPE_AGENT_ENABLED: true
      PYROSCOPE_APPLICATION_NAME: ${PYROSCOPE_NAME}
      PYROSCOPE_PROFILER_ALLOC: 512k
      PYROSCOPE_SERVER_ADDRESS: ${PYROSCOPE_SERVER_ADDRESS}
      PYROSCOPE_BASIC_AUTH_USER: ${PYROSCOPE_BASIC_AUTH_USER}
      PYROSCOPE_BASIC_AUTH_PASSWORD: ${PYROSCOPE_BASIC_AUTH_PASSWORD}
      PYROSCOPE_TRACE_PROFILING_ENABLED: true
      OTEL_RESOURCE_ATTRIBUTES: "service.name=genealogy,deployment.environment=prod"
      OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
      #OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp-gateway-prod-gb-south-0.grafana.net/otlp"
      #OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana_alloy:4318"
      OTEL_LOGS_EXPORTER: none
      OTEL_SERVICE_NAME: genealogy
      MEDIA_PATH: /tmp/Medias/
      UPLOAD_PATH: /tmp/Upload/
      EXTERNAL_ASSETS_PATH: /tmp/external-assets
      CUSTOM_JS_FILE: "javascript/faro.js"
      PLAY_FILTERS_HOSTS: genealogie.parois.net
      PROTOCOL: https://
      APP_NAME: Parois.net
      JAVA_OPTS: >-
        -Dlogger.file=/opt/logback.xml
        -javaagent:/opt/grafana-opentelemetry-java.jar
        -Dotel.javaagent.extensions=/opt/pyroscope-otel-javaagent-extension.jar
        -Dotel.instrumentation.common.default-enabled=true
        -Dotel.instrumentation.opentelemetry-annotations.enabled=true
        -Dotel.instrumentation.methods.enabled=true
        -Dotel.bsp.max.queue.size=4096
        -Dotel.bsp.max.export.batch.size=1024
        -Dotel.bsp.schedule.delay=1000
    ports:
      - 127.0.0.1:9123:9123
    volumes:
      - ./Medias/:/tmp/Medias
      - ./Assets/:/tmp/external-assets
      - ./Upload/:/tmp/Upload
      - ./Config/logback.xml:/opt/logback.xml:ro
      - ./otel/grafana-opentelemetry-java.jar:/opt/grafana-opentelemetry-java.jar:ro
      - ./otel/pyroscope-otel-javaagent-extension.jar:/opt/pyroscope-otel-javaagent-extension.jar:ro
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "50m"
        max-file: "3"

networks:
  dockernet:
    external: true
