
networks:
  loki:

services:
  carbon-relay-ng:
    image: grafana/carbon-relay-ng:1.5.3
    container_name: carbon-relay-ng
    volumes:
      - ./carbon-relay/etc:/conf
      - ./carbon-relay/log:/var/log
    ports:
      - "127.0.0.1:2103:2003"
      #- "127.0.0.1:3300:8081"
    networks:
      - loki
    restart: always
    environment:
      - TZ=Europe/London
      - GRAFANA_NET_USER_ID=${GRAFANA_NET_USER_ID}
      - GRAFANA_NET_API_KEY=${GRAFANA_NET_API_KEY}
      - LOG_LEVEL=info
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd:1.1.10-5

    volumes:
      - ./graphite/storage:/opt/graphite/storage
      - ./graphite/conf:/opt/graphite/conf
      - ./graphite/statsd:/opt/statsd/config
      - ./graphite/log:/var/log
    ports:
      - "127.0.0.1:7000:80"
      #- "127.0.0.1:2003-2014:2003-2004" # direct
      - "127.0.0.1:2003-2004:2013-2014" # carbon-relay
      - "127.0.0.1:2023-2024:2023-2024"
      - "127.0.0.1:8125:8125/udp"
      - "127.0.0.1:8126:8126"
    networks:
      - loki
    restart: always
    environment:
      - TZ=Europe/London
      - GOCARBON=1
      - RELAY=1
      - GRAPHITE_WSGI_REQUEST_TIMEOUT=120
      - GRAPHITE_WSGI_THREADS=1
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}" 

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/loki-config.yml -config.expand-env=true
    networks:
      - loki
    volumes:
      - ./loki/conf:/etc/loki
      - loki-storage:/loki
      - ./loki/rules:/etc/loki/rules
    restart: always
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_BUCKET=${S3_BUCKET}
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#  promtail:
#    image: grafana/promtail:3.3.2
#    container_name: promtail
#    ports:
#      - "127.0.0.1:1514:1514/tcp"
#      - "127.0.0.1:1514:1514/udp"
#      - "127.0.0.1:9080:9080"
#    volumes:
#      - ./promtail/log:/var/log
#      - ./promtail/conf:/etc/promtail
#      - /var/lib/docker/containers:/host/var/lib/docker/containers
#      - /home/containers/Abraracourcix/nginx/logs:/host/var/log/nginx
#      - /var/log/php-fpm:/host/var/log/php-fpm
#      - /var/log/mariadb:/host/var/log/mariadb
#      - /var/log/journal:/host/var/log/journal
#      - /etc/machine-id:/etc/machine-id
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - loki
#    restart: always
#    logging:
#      options:
#        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

#  promtail-remote:
#    image: grafana/promtail:3.3.2
#    container_name: promtail-remote
#    ports:
#      - "127.0.0.1:1515:1514/tcp"
#      - "127.0.0.1:1515:1514/udp"
#      - "127.0.0.1:9081:9080"
#    volumes:
#      - ./promtail-remote/log:/var/log
#      - ./promtail-remote/conf:/etc/promtail
#      - /var/lib/docker/containers:/host/var/lib/docker/containers
#      - /home/containers/Abraracourcix/nginx/logs:/host/var/log/nginx
#      - /var/log/php-fpm:/host/var/log/php-fpm
#      - /var/log/mariadb:/host/var/log/mariadb
#      - /var/log/journal:/host/var/log/journal
#      - /home/containers/Abraracourcix/nginx/logs:/host/var/log/nginx-docker
#      - /etc/machine-id:/etc/machine-id
#    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
#    networks:
#      - loki
#    restart: always
#    environment:
#      - LOKI_ID=${LOKI_ID}
#      - LOKI_TOKEN=${LOKI_TOKEN}
#    logging:
#      options:
#        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - loki
    environment:
      - GF_LOG_LEVEL=debug
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.debroglie.net
      - GF_SMTP_ENABLED=true
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  alloy:
    container_name: grafana_alloy
    volumes:
      - ./alloy/conf:/etc/alloy
      - /var/lib/docker/containers:/host/var/lib/docker/containers
      - /home/containers/Abraracourcix/nginx/logs:/host/var/log/nginx
      - /var/log/php-fpm:/host/var/log/php-fpm
      - /var/log/mariadb:/host/var/log/mariadb
      - /var/log/journal:/host/var/log/journal
    environment:
      - LOKI_ID=${LOKI_ID}
      - LOKI_TOKEN=${LOKI_TOKEN}
    ports:
      - 12345:12345
    image: grafana/alloy:latest
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'
    networks:
      - loki
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

volumes:
  grafana-storage:
    name: grafana-storage
    external: true
  loki-storage:
    name: loki-storage
    external: true
