version: '3.8'

networks:
  loki:

services:
  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd:1.1.10-5

    volumes:
      - ./graphite/storage:/opt/graphite/storage
      - ./graphite/conf:/opt/graphite/conf
      - ./graphite/statsd:/opt/statsd/config
      - ./graphite/log:/var/log
    ports:
      - "127.0.0.1:7000:80"
      - "127.0.0.1:2003-2004:2003-2004"
      - "127.0.0.1:2023-2024:2023-2024"
      - "127.0.0.1:8125:8125/udp"
      - "127.0.0.1:8126:8126"
    networks:
      - loki
    restart: always
    environment:
      - TZ=Europe/London
      - GOCARBON=1
      - GRAPHITE_WSGI_REQUEST_TIMEOUT=120
      - GRAPHITE_WSGI_THREADS=1
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}" 

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
      - '--log.level=debug'
    volumes:
      - ./alertmanager/config:/etc/alertmanager
    ports:
      - "127.0.0.1:9093:9093"
    networks:
      - loki
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    volumes:
      - ./loki/conf:/etc/loki
      - loki-storage:/loki
      - ./loki/rules:/etc/loki/rules
    depends_on:
     - alertmanager
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  promtail:
    image: grafana/promtail:2.9.4
    ports:
      - "127.0.0.1:1514:1514/tcp"
      - "127.0.0.1:1514:1514/udp"
      - "127.0.0.1:9080:9080"
    volumes:
      - ./promtail/log:/var/log
      - ./promtail/conf:/etc/promtail
      - /var/lib/docker/containers:/host/var/lib/docker/containers
      - /var/log/nginx:/host/var/log/nginx
      - /var/log/php-fpm:/host/var/log/php-fpm
      - /var/log/mariadb:/host/var/log/mariadb
      - /var/log/journal:/host/var/log/journal
      - /etc/machine-id:/etc/machine-id
      - /home/containers/Abraracourcix/nextcloud/nextcloud/www/data:/host/var/log/nextcloud
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.debroglie.net
      - GF_SMTP_ENABLED=true
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

volumes:
  grafana-storage:
    name: grafana-storage
    external: true
  loki-storage:
    name: loki-storage
    external: true
