version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.24.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data:Z
      - /etc/timezone:/etc/timezone:ro,Z
      - /etc/localtime:/etc/localtime:ro,Z
      - /home/git/.ssh:/ssh:Z

    ports:
      - "127.0.0.1:3003:3003"
      - "2222:2222"

    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
