version: '3.8'

networks:
  loki:

services:
  promtail:
    image: grafana/promtail:3.5.0
    container_name: promtail
    ports:
      - "1514:1514/tcp"
      - "1514:1514/udp"
      - "9080:9080"
    volumes:
      - ./promtail/log:/var/log
      - ./promtail/conf:/etc/promtail
      - /var/lib/docker/containers:/host/var/lib/docker/containers
      - /var/log/journal:/host/var/log/journal
      - /opt/containers/MediaCentre/nginx/logs/:/host/var/log/nginx
      - /etc/machine-id:/etc/machine-id
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
    restart: always
    logging:
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

