version: "3"

services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:4.8.1
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./log:/var/log
    ports:
      - 5514:5514/udp
      - 127.0.0.1:601:6601/tcp
#      - 127.0.0.1:6514:6514/tcp
    restart: never

